### ISSUE TITLE
Quote shown as zero before allowance set

### ISSUE THREAD

**Issue by xykota** [sifiorg/sifi#444] opened 2023-11-22 05:56 UTC
<img width="499" alt="image" src="https://github.com/sifiorg/sifi/assets/128569957/83fb78d8-3c38-4ef9-a727-7113092ddb6f">

**Comment by xykota** [comment] 2023-11-22 06:04
<img width="510" alt="image" src="https://github.com/sifiorg/sifi/assets/128569957/aef6f2ef-0f01-4c84-b73f-38c570d65e2b">

**Comment by boriskubrik** [comment] 2023-11-22 20:56
Duplicate of #415

**Closed by boriskubrik** 2023-11-22 20:56 UTC
Labels: frontend
